### PR TITLE
made build and link work again.

### PR DESCRIPTION
**Pull request by dsizzle**
- fixed all Archive methods with incorrect signatures
- fixed character replacement calls for BStrings
- added #ifdef around function declaration in MyListView that was causing link error
- added missing -lstdc++ in Makefile
- removed extra cpp file in Makefile that isn't part of the main project

Notes:
- crashes on first startup due to missing preferences. Works on 2nd or 3rd run.
- missing some .jpg files so a few error dialogs pop up

### CODE REVIEW

**Comment by dsizzle** [comment]
> crashes on first startup due to missing preferences. Works on 2nd or 3rd run.

Not entirely true - there seems to be a race condition perhaps that causes sporadic crashes on startup.

**Comment by humdingerb** [comment]
Currently only launches from Terminal. Double-click has it crash, I'll file a ticket.
Seeing the GUI... my highschool-math-self's nightmare... :)

**Comment by dsizzle** [comment]
it is quite a nightmare GUI - I had some regrets for bringing it back to life :rofl:

**Comment by humdingerb** [comment]
Let's rename to FrankenCalc.

**Pull request merged**
